### ISSUE TITLE
OCP\Files\NotFoundException: /xxxxxx/files/Documents/QuickNote/search:

### ISSUE THREAD

**Issue by Githopp192** [CarnetApp/CarnetNextcloud#1]
Current Environment: centos-release-7-5.1804.4.el7.centos.x86_64
NC Release: 13.0.6

-->

Error | index | OCP\Files\NotFoundException: /xxxxxxx/files/Documents/QuickNote/search:/var/www/html/nextcloud/lib/private/Files/Node/Folder.php - line 133:  OC\Files\Node\Root->get('/xxxx/files/...')/var/www/html/nextcloud/apps/carnet/lib/Controller/NoteController.php - line 334:  OC\Files\Node\Folder->get('search //')[internal function] OCA\Carnet\Controller\NoteController->createNote()/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 161:  call_user_func_array(Array, Array)/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 91:  OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Carnet\Controller\NoteController), 'createNote')/var/www/html/nextcloud/lib/private/AppFramework/App.php - line 115:  OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Carnet\Controller\NoteController), 'createNote')/var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:  OC\AppFramework\App  main('OCA\\Carnet\\Cont...', 'createNote', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)/var/www/html/nextcloud/lib/private/Route/Router.php - line 297:  call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)/var/www/html/nextcloud/lib/base.php - line 999:  OC\Route\Router->match('/apps/carnet/no...')/var/www/html/nextcloud/index.php - line 42:  OC  handleRequest(){main} | 15 minutes ago
-- | -- | -- | --
Error | PHP | Use of undefined constant relativePath - assumed 'relativePath' at /var/www/html/nextcloud/apps/carnet/lib/Command/Search.php#100 | 16 minutes ago
Error | PHP | Use of undefined constant relativePath - assumed 'relativePath' at /var/www/html/nextcloud/apps/carnet/lib/Command/Search.php#100 | 16 minutes ago
Error | PHP | Uninitialized string offset: 0 at /var/www/html/nextcloud/lib/private/Files/Node/Node.php#290 | 16 minutes ago
Error | PHP | Undefined variable: userId at /var/www/html/nextcloud/apps/carnet/lib/Command/Search.php#48 | 16 minutes ago
Error | PHP | Use of undefined constant relativePath - assumed 'relativePath' at /var/www/html/nextcloud/apps/carnet/lib/Command/Search.php#100 | 16 minutes ago
Error | PHP | Use of undefined constant relativePath - assumed 'relativePath' at /var/www/html/nextcloud/apps/carnet/lib/Command/Search.php#100 | 16 minutes ago
Error | PHP | Uninitialized string offset: 0 at /var/www/html/nextcloud/lib/private/Files/Node/Node.php#290 | 16 minutes ago
Error | PHP | Undefined variable: userId at /var/www/html/nextcloud/apps/carnet/lib/Command/Search.php#48

**Comment by AaronADev** [comment]
@Githopp192 Just curious, did this happen immediately after you enabled the application or did this start happening over time. I couldn't get it to work for some reason, I didn't investigate though. I am going to re-enable and see if the logs  you posted are similar to mine.

**Comment by PhieF** [comment]
The app doesn't work at all ? What do you do to get your issue ?

**Comment by AaronADev** [comment]
@PhieF Well, just by installing it and attempting to access it through the menu bar it consistently gives errors after each of the requests for the app to perform any action. It's obviously broken  somewhere or there is additional setup needed, I'm not quite sure. 

In my case I am using NextCloud Snap 14.0/candidate, which has worked great with everything else that I have tried. Would the Snap be an issue for this application? Wouldn't think so...

@Githopp192 Any chance you are running a snap as well?

**Comment by PhieF** [comment]
I've found the source of the issue, it's indeed coming from snap, thanks for the report ! 
it will soon be fixed

**Comment by PhieF** [comment]
snap fixed with #dc652534ee38806aef43f0262f77355f9610d3ac

**Comment by AaronADev** [comment]
@PhieF Awesome, thanks for the fix. I'm gonna give it another shot and see how it goes. If other issues arise I'll report it back to you in an issue so you are aware.

**Comment by Githopp192** [comment]
i think old threat - i'm now on NC 19.0.5 - will close this ticket
