### ISSUE TITLE
Export note as html

### ISSUE THREAD

**Issue by sunjam** [CarnetApp/CarnetNextcloud#12]
Please add the ability to export notes as html.

**Comment by rstruminski** [comment]
Wouldn't it be possible (and nicer?) to save the notes as .rtf files or something like that? That way you could easily open and edit them in many text editors. Notes would be more platform/app-independent and easily shareable if they weren't packed into an .sqd file that no other app can directly open or edit.

**Comment by PhieF** [comment]
Done !
