### ISSUE TITLE
"export all notes" from settings doesn't respect directory of nextcloud installation

### ISSUE THREAD

**Issue by vacy** [CarnetApp/CarnetNextcloud#125]
"export all notes" from settings doesn't respect directory of nextcloud installation
![image](https://user-images.githubusercontent.com/9817869/92817286-b55bfc00-f3c6-11ea-85bb-a3ef6066d965.png)

I got nextcloud in example.org/nextcloud installed, but the Export all notes button redirects wrong.

Quickfix in "lib/Controller/NoteController.php" --->  public function downloadArchive(){
> return new RedirectResponse("../../../../../index.php/apps/files/ajax/download.php?files=".$this->getNotePath());

to

>$tmp = substr($_SERVER['REQUEST_URI'],1);
>$tmp = strchr($tmp,"/", "true");
>if ($tmp == "index.php") {
>  $tmp = "";
>}
>return new RedirectResponse("../../../../../".$tmp."/index.php/apps/files/ajax/download.php?files=".$this->getNotePath());

**Comment by PhieF** [comment]
Thanks I will test this code, but I wanted to do a better thing here ! 

If you want you can make a pull request to have your name in commits ! :)

**Comment by vacy** [comment]
hooray, thank you. i close issue.
