### ISSUE TITLE
[Bug] Error occured: TypeError: fullDB is null

### ISSUE THREAD

**Issue by TMaddox** [CarnetApp/CarnetNextcloud#130]
**Describe the bug**
If I open any note this occures: Error occured: TypeError: fullDB is null

**To Reproduce**
1. open any note
2. receive the following error: Error occured: TypeError: fullDB is null

**Expected behavior**
No error is reported/ no error occurs

**Screenshots**
![image](https://user-images.githubusercontent.com/20703314/95018075-83545780-065d-11eb-82f1-c757614d1438.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser firefox
 - Version 81.0

# **Please let me know if this could mean that I loose my notes, I got a whole bunch of users using carnet in production. Thanks!**

**Comment by PhieF** [comment]
Hi, thanks for the report...
can you please open the web console: f12 on firefox, and send me the content ? Can you browse to your carnet folder on nextcloud and tell me if you can find your notes here as sqd files ?

Thank you

**Comment by TMaddox** [comment]
Pasted the log in this file:
[carnet error.log](https://github.com/CarnetApp/CarnetNextcloud/files/5347220/carnet.error.log)

My carnet foler is .notes/QuickNote, but there are some cache file in .carnet (which was automatically created)
![image](https://user-images.githubusercontent.com/20703314/95448702-06c6bf00-0964-11eb-9796-b032088be80d.png)

But yes, I can confirm that I have all my notes as *.sqd files located in .notes/QuickNote/*.sql

Thanks

**Comment by PhieF** [comment]
Does your keywords appears on the left panel of Carnet when you start Carnet ?

Thanks

**Comment by TMaddox** [comment]
I couldn't figure out what keywords are till now, but this is what I see:
![image](https://user-images.githubusercontent.com/20703314/96350154-90893180-10b4-11eb-9a70-1dcf1f3d83c5.png)

**Comment by TMaddox** [comment]
Any update on this? I still have the same issue, even on the newest version (0.23.7) @PhieF

**Comment by PhieF** [comment]
Do you think you could create me an account and send me credentials to phie@phie.ovh ?

**Comment by TMaddox** [comment]
Problem solved via purging all notes and reentering them manually. Thanks!
