### ISSUE TITLE
Cannot open notes in Nextcloud 

### ISSUE THREAD

**Issue by roelfrenkema** [CarnetApp/CarnetNextcloud#132]
Please report every bug related to the Android application here
https://github.com/PhieF/CarnetAndroid/

Cannot open notes in Nextcloud

**To Reproduce**
1. Go to 'carnet'
2. Click on 'note'
3. Window opens
4. Keeps loading

**Expected behavior**
show note

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Debian 10]
 - Browser [Firefox]
 - Version [Latest]

From the nextcloud log:

[PHP] Error: Error: file_put_contents(): Filename cannot be empty at /var/www/nextcloud/apps/carnet/lib/Controller/NoteController.php#1064 at <<closure>>

0. <<closure>>
   OC\Log\ErrorHandler::onError(2, "file_put_conten ... y", "/var/www/nextcl ... p", 1064, {editUniqueID: " ... e})
1. /var/www/nextcloud/apps/carnet/lib/Controller/NoteController.php line 1064
   file_put_contents("", null)
2. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 169
   OCA\Carnet\Controller\NoteController->openNote()
3. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 100
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Carnet\Contr ... }}, "openNote")
4. /var/www/nextcloud/lib/private/AppFramework/App.php line 152
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Carnet\Contr ... }}, "openNote")
5. /var/www/nextcloud/lib/private/Route/Router.php line 308
   OC\AppFramework\App::main("OCA\\Carnet\\Controller\\NoteController", "openNote", OC\AppFramework\ ... {}, {action: null,_r ... "})
6. /var/www/nextcloud/lib/base.php line 1009
   OC\Route\Router->match("/apps/carnet/note/open")
7. /var/www/nextcloud/index.php line 37
   OC::handleRequest()

GET /apps/carnet/note/open?path=untitled%207%20SJ.sqd
from 143.176.83.122 by ncp at 2020-10-08T10:00:13+00:00

**Comment by PhieF** [comment]
Hi

did it work before ?

Thanks !

**Comment by roelfrenkema** [comment]
seems to have been temporry. closing the issue.
