### ISSUE TITLE
Carnet does not activate after update

### ISSUE THREAD

**Issue by lpoujoulat** [CarnetApp/CarnetNextcloud#133]
After updating to 0.23 in Nextcloud 19.0.4, impossible to activate Carnet; Error message in log states:

{"reqId":"VW7MMLoTYylQYDbNkvC8","level":3,"time":"2020-11-05T22:20:04+00:00","remoteAddr":"**********,"user":"*****","app":"no app in context","method":"GET","url":"/apps/files","message":{"Exception":"Error","Message":"Class 'OCA\\Carnet\\AppInfo\\Exception' not found","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/legacy/OC_App.php","line":266,"function":"require_once"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_App.php","line":155,"function":"requireAppFile","class":"OC_App","type":"::"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_App.php","line":128,"function":"loadApp","class":"OC_App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":996,"function":"loadApps","class":"OC_App","type":"::"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/carnet/appinfo/app.php","Line":14,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0","version":"19.0.4.2","id":"5fa47ac669ad5"}

Reinstalling Carnet does not solve the problem.

**Comment by ashcoft** [comment]
so do i

**Comment by wouterVE** [comment]
I'm facing the same issue in Nextcloud 19.0.3

> {"reqId":"r2zTeueuf8PkqnWOIqTx","level":3,"time":"2020-11-06T08:10:49+00:00","remoteAddr":"********","user":"**************","app":"no app in context","method":"GET","url":"/apps/files","message":{"Exception":"Error","Message":"Class 'OCA\\Carnet\\AppInfo\\Exception' not found","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/legacy/OC_App.php","line":266,"function":"require_once"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_App.php","line":155,"function":"requireAppFile","class":"OC_App","type":"::","args":["carnet"]},{"file":"/var/www/nextcloud/lib/private/legacy/OC_App.php","line":128,"function":"loadApp","class":"OC_App","type":"::","args":["carnet"]},{"file":"/var/www/nextcloud/lib/base.php","line":997,"function":"loadApps","class":"OC_App","type":"::","args":[]},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/apps/carnet/appinfo/app.php","Line":14,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36 OPR/72.0.3815.186","version":"19.0.3.1","id":"5fa5050fc6f82"}

My environment:

- PHP 7.3

- Apache 2.4

- Debian 10

**Comment by PhieF** [comment]
Should be fixed with latest release ! Thanks for the report

**Comment by wouterVE** [comment]
Thanks! I can confirm the error is gone after updating from 0.23.0 to 0.23.4.
Now it's possible to enable Carnet.

**Comment by PhieF** [comment]
Great !
