### ISSUE TITLE
Google Keep import doesn't work for checklists

### ISSUE THREAD

**Issue by insi9nis** [CarnetApp/CarnetNextcloud#142]
**Describe the bug**
You probably already know this, as I don't see any code for "listContent" or "isChecked" in google-converter.js, but I also didn't see an issue created yet.

My Keep notes that are only text seemed to import fine.  All of my checklist notes show up blank (i.e., title only) on import.

**To Reproduce**
1) Went to google takeout, unchecked everything, only checked Keep, kept default settings, nabbed zip.
2) Fed the zip to Carnet, with default settings
[note:  I have no idea what "Once the archive is downloaded: (o) Google Keep; ( ) Carnet" setting is supposed to do; I left it on the default of Google Keep, but I'm not sure what the alternative would do differently.]
3) When it was done, I looked at the imported notes, and they are as described in the bug section above.
 
**Expected behavior**
Ideally, I would have checklist notes that matched Google Keep's, with unchecked and checked displayed in the same manner.

**Screenshots**
I don't think it's necessary, but will provide if asked.

**Desktop (please complete the following information):**
 - OS: [Windows 10 Build 1903]
 - Browser [Chrome Version 87.0.4280.141 (Official Build) (64-bit)]
 - Version [Carnet 0.23.7 on Nextcloud 20.0.5 on Ubuntu 20.04.1]

**Comment by PhieF** [comment]
should be fixed with https://github.com/CarnetApp/CarnetElectron/pull/52
