### ISSUE TITLE
Fehler beim aktivieren aus dem Appstore

### ISSUE THREAD

**Issue by Integral31** [CarnetApp/CarnetNextcloud#145]
Hello, when installing the app from the appstore, the following message appears:
There is an error with the administration. It is not possible to continue.
App Carnet could not be extracted

Thanks in advance.

Hallo, bei der Installation der App aus dem Appstore kommt folgende Meldung: 
Es ist ein Fehler bei der Anfrage aufgetreten. Es kann nicht fortgefahren werden.
Could not extract app carnet

Danke vorab.

Frank

 - OS: Linux Mint 20.1
 - Browser Iron
 - Version Version 85.0.4350.0

**Comment by diqidoq** [comment]
Possible duplicate of -> https://github.com/CarnetApp/CarnetNextcloud/issues/143

**Comment by PhieF** [comment]
Indeed, it seems to be a bug with nextcloud

please download it from here https://github.com/CarnetApp/CarnetNextcloud/releases

and extract it to your apps directory, then enable it on nextcloud
