### ISSUE TITLE
Correction in NoteController.php @ line 632

### ISSUE THREAD

**Issue by hobbsecky** [CarnetApp/CarnetNextcloud#150]
https://github.com/CarnetApp/CarnetNextcloud/blob/3335cbfa6d9b424c7ebfa983c123fb9a81572003/lib/Controller/NoteController.php#L632

I changed mine to:

`        $metadataFromCache = $cache->getFromCache($paths);`

No more errors in my logs after the change.

Peace out.

**Comment by PhieF** [comment]
Thanks for the tip
