### ISSUE TITLE
Nextcloud 22 Support

### ISSUE THREAD

**Issue by mvhirsch** [CarnetApp/CarnetNextcloud#160]
What's needed to officially support Nextcloud 22? 
Workaround like in #159 seems to be spooky to me.

**Comment by PhieF** [comment]
Hi

I will try to work on that tonight

**Comment by PhieF** [comment]
I've found the source of the problem, it's now fixed, I will make a release on the nextcloud app store very soon

**Comment by PhieF** [comment]
Should be ok now, feel free to reopen this issue if you are still having problems !

**Comment by mvhirsch** [comment]
Thank you very much. Works like a charm!
