### ISSUE TITLE
app can't install/update on 0.24.3

### ISSUE THREAD

**Issue by harukin0731** [CarnetApp/CarnetNextcloud#177]
I got this error when try install new version.
`Error: Could not extract app carnet: Out-of-path file extraction {/tmp/oc_tmp_Xo8E66-folder/carnet/templates/CarnetElectron --> /home/phieubuntu/Dev/Code/Carnet/CarnetElectron}`

oh... absolute path.....

**Comment by pdcatbsc** [comment]
I get a similar message.  I've looked at the log file, but don't understand what it is saying.

**Comment by PhieF** [comment]
Should be ok with 0.24.4 !

**Comment by harukin0731** [comment]
OK! it works correctly!! Thank you for quick response!!
