### ISSUE TITLE
"metadata" is type String, but exceeding the 4.000 length limit. 

### ISSUE THREAD

**Issue by cr9christi9n** [CarnetApp/CarnetNextcloud#185]
Hi there,
Nextcloud version = 24.01
Debian 11
(all the securities and configuration tests in my interface are OK)

Impossible to download and install "Carnet" from my nextcloud/apps interface.
I've got the following message
`Column "oc_carnet_metadata"."metadata" is type String, but exceeding the 4.000 length limit. `

many thanks in advance, regards.
Cr9c

**Comment by valentino-sm** [comment]
¯\_(ツ)_/¯

**Comment by valentino-sm** [comment]
¯\\\_(ツ)\_/¯

**Comment by PhieF** [comment]
I'm on it, I guess I've found how to fix it yesterday, will update as soon as possible

**Comment by PhieF** [comment]
Great ! Thanks !

Le 8 juin 2022 22:45:37 GMT+02:00, Melissa Draper ***@***.***> a écrit :
