### ISSUE TITLE
compatible version for Nextcloud v24*

### ISSUE THREAD

**Issue by woll-knaeuel** [CarnetApp/CarnetNextcloud#186]
Hello
The webupdater is already providing a stable update to the next release of Nextcloud v24.
Unfortunatelly there is no compatibility for carnet app. 
When will there be a compatible version of carnet for Nextcloud 24.0.1 or higher?
Thx
<img width="428" alt="Bildschirmfoto 2022-05-27 um 19 43 13" src="https://user-images.githubusercontent.com/38803244/170763617-81edb17d-cfdd-491f-bfca-6dd2525fe743.png">

**Comment by stefanocudini** [comment]
https://github.com/CarnetApp/CarnetNextcloud/blob/main/appinfo/info.xml#L36

when support nextcloud 24?

**Comment by yazeed44** [comment]
I'm locked out of Carnet because I upgraded to v24. Are there any quick fixes?

**Comment by meldra** [comment]
There's a fix for a data problem going out "soon" according to @PhieF on #185 so im guessing compatibility might happen with that.

**Comment by woll-knaeuel** [comment]
Version 0.24.5 is available and should be compatible with Nextcloud v24.
@PhieF Thanks for the fix!

**Comment by PhieF** [comment]
You're welcome !

**Comment by fafische** [comment]
The App still tells, not to support Nextcloud >=23.

![grafik](https://user-images.githubusercontent.com/3582045/173020774-e6e72708-d603-486a-b9fa-30e39a22f555.png)

**Comment by PhieF** [comment]
Was the update available ?

Le 10 juin 2022 10:07:31 GMT+02:00, fafische ***@***.***> a écrit :

**Comment by fafische** [comment]
Yes. The update displayed and installed just befor. Mybe it is a bug of nextcloud, not to recheck compatibility after app update?
I enabled the app using the button vor untested apps and it seems to work fine.
