### ISSUE TITLE
Nextcloud 25 compatibility

### ISSUE THREAD

**Issue by zurchpet** [CarnetApp/CarnetNextcloud#198]
Carnet does not work on Nextcloud Version 25.

**Comment by MartinixH** [comment]
as "hotfix" I commented out every line starting with 'app_version' in /var/www/html/nextcloud/custom_apps/carnet/lib/Controller/PageController.php

and lines 244-248 and 251 in /var/www/html/nextcloud/custom_apps/carnet/lib/Controller/NoteController.php

then it started working, but it print errors in nextcloud.log that 'app_version' variable is not set. So it's not final solution, but it works

**Comment by zurchpet** [comment]
Thanks @MartinixH I'll give it a try.

**Comment by zurchpet** [comment]
Cool. I can confirm, that the modifications @MartinixH suggested did make it work again.

**Comment by T0ytoy** [comment]
Thanks for the hack @MartinixH, I hope an official fix will come soon ;)

**Comment by T0ytoy** [comment]
I identified the issue, php class OCP\App is no longer available, legacy support is there : OC_App (https://github.com/nextcloud/server/blob/master/lib/private/legacy/OC_App.php)

I opened a pull request here : https://github.com/CarnetApp/CarnetNextcloud/pull/199

Maybe it can eventually be merge into the main branch, in the meantime you can take what's inside to fix your files in your own nextcloud ;)

**Comment by MartinixH** [comment]
@T0ytoy nice work! I identified that missing class too, but didn't find that legacy support or any other easy fix. Hope that will be merged soon :-)

**Comment by hackitz** [comment]
thank you worked like a charm,  hopefully an update comes along.

**Comment by hackitz** [comment]
looks like PhieF, just updated  app info.xml
so looks like a fix is coming, thank you so much.

**Comment by PhieF** [comment]
in comiiiiing

**Comment by PhieF** [comment]
released
