### ISSUE TITLE
Nextcloud 27 support

### ISSUE THREAD

**Issue by AceDenghar** [CarnetApp/CarnetNextcloud#207]
Hi,

First of all, nice job for this app !

I'm using a nextcloud 27 and last Carney's version is shown as not tested.

'Server version 26 or lower is required'

Wil it be safe to activate ?

Thanks.

**Comment by TheOfficialMrBlah** [comment]
Hi,

I've updated Nextcloud to 27.0.1 and enabled Carnet, seems to work fine.

**Comment by PhieF** [comment]
so weird I thought I've updated it, will do tonight

**Comment by TheOfficialMrBlah** [comment]
> so weird I thought I've updated it, will do tonight

Thank you very much!

**Comment by PhieF** [comment]
all good
