### ISSUE TITLE
Notes created as Markdown with CarnetAndroid 0.25.0 aren't shown

### ISSUE THREAD

**Issue by vaxul** [CarnetApp/CarnetNextcloud#211]
**Describe the bug**
If I create notes with the new Markdown Editor within CarnetAndroid v0.25.0, the aren't shown within the CarnetNextcloud app.

**Expected behavior**
At least show the raw Mardown file in CarnetNextcloud, even if an editor is not finished.

Thanks for the app and best regards 👋

**Comment by CyberMinion** [comment]
Are you using NextCloud v28? If so, have you tried the unofficial fix, discussed in another thread? See: https://github.com/CarnetApp/CarnetNextcloud/issues/214

One change was proposed in there which was intended to fix an issue with markdown notes.
