### ISSUE TITLE
'My Account' button doesn't work / can't delete account

### ISSUE THREAD

**Issue by jackrgm** [CarnetApp/CarnetNextcloud#213]
I would like to delete an account of mine on https://carnet.live, but on the setting page it seems that there's a button for "My Account" but it doesn't do anything when clicked/tapped (neither does "Logout").

**Comment by PhieF** [comment]
can you try going there https://carnet.live/settings/user ?

**Comment by jackrgm** [comment]
Yup, that works, and I was able to mark my account for deletion there. Brilliant, thank you.

I'll mark this as closed as it solves my root problem, but feel free to reopen if you want to track the button fixing (i.e. for other users).
