### ISSUE TITLE
Nextcloud 29.0.3 claims to be incompatible with carnet - any update ahead?

### ISSUE THREAD

**Issue by kariburger** [CarnetApp/CarnetNextcloud#222]
I would like to update my Nextcloud from 29.0.0 to 29.0.3 - but I don't want to loose my Carnet app.
Did anybody try to install the existing Carnet app with Nextcloud 29.0.3?
Did anybody find the relevant files to change, to get it compatible?

Thanks,
Achim

**Comment by heegard** [comment]
I would also like to update 28.0.7 -> 29.0.3

**Comment by h3n3b0sch** [comment]
Sort of same here, I was hoping to install but NC says server version is to high...

h3n3

**Comment by devplan44** [comment]
@Alexandre Roux

Could you please let us know.
Do you intent to make carnet compatible with Nextcloud 29?

(At the NC App store it says: Last updated
4 months, 2 weeks ago)

**Comment by PhieF** [comment]
I will be able to work on this in about 10 days, it will be updated

**Comment by PhieF** [comment]
done

**Comment by j-mcdougall** [comment]
Thank you PhieF.  We appreciate your work on this.
