### ISSUE TITLE
Carnet search does not work on Nextcoud

### ISSUE THREAD

**Issue by rakarisbakaris** [CarnetApp/CarnetNextcloud#97]
**Describe the bug**
I have configured Fulltext search on Elastic basis. User’s file search on Carnet is working. But there is a problem with search on notes application Carnet from Web interface (android app search works fine). The search circle moves around without getting any search results.

**To Reproduce**
1. Go to 'Carnet application on Nextcloud' and open 'Browse'. You will see your notes folder or notes
2. Click on 'Search'
3. See 'circle which moves around'

**Expected behavior**
Search results

**Screenshots**
https://imgur.com/M58kq3Q

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Firefox, Edge]
 - Version [newest]

**Smartphone (please complete the following information):**
 - Device: [huawei p9 lite 2017]
 - OS: [Android 8.00]
 - Browser [Mozilla]
 - Version [newest]

**Server**
 - OS NethServer 7.7.1908
 - App NextCloud 1.8.2
  - App Carnet 0.19.1

**Some logs**
*This was at time when indexing was configured / started*

> {“reqId”:“XheYfCtTMDSS@qb9gAtSLAAAAAQ”,“level”:3,“time”:“2020-01-09T21:17:48+00:00”,“remoteAddr”:“192...50”,“user”:“admin”,“app”:“PHP”,“method”:“GET”,“url”:"/index.php/apps/carnet/settings",“message”:“Undefined index: nc_version at /usr/share/nextcloud/apps/carnet/templates/settings.php#28”,“userAgent”:“Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0”,“version”:“17.0.2.1”,“id”:“5e183158a3a42”}

*A lot of requests such this*

> 192.*.*.5 - - [05/Jan/2020:17:48:28 +0200] "GET /nextcloud/index.php/apps/carnet/notes/getSearchCache HTTP/1.1" 200 12

**Comment by PhieF** [comment]
I've changed search behavior, it should work better in next version ! We will reopen if you still have an issue

Thanks for the report !! And sorry for answering that late :(
